const screens = {
  login: 'LOGIN',
  signup: 'SIGN_UP',
  welcome: 'WELCOME',
  equipmentList: 'EQUIPMENT_LIST',
  home: 'HOME',
  main: 'MAIN',
  onBoarding: 'ON_BOARDING',
  profile: 'PROFILE',
  templatesAndSetup: 'TEMPLATES_AND_SETUP',
  equipmentModelForm: 'EQUIPMENT_MODEL_FORM',
  equipmentModelDetails: 'EQUIPMENT_MODEL_DETAILS',
  serviceIntervalForm: 'SERVICE_INTERVAL_FORM',
  serviceIntervalDetails: 'SERVICE_INTERVAL_DETAILS',
  serviceTaskForm: 'SERVICE_TASK_FORM',
  serviceTaskDetails: 'SERVICE_TASK_DETAILS',
  serviceTemplateDetails: 'SERVICE_TEMPLATE_DETAILS',
  serviceTemplateForm: 'SERVICE_TEMPLATE_FORM',
  forgotPassword: 'FORGOT_PWD',
  partsForm: 'PARTS_FORM',
  partsDetails: 'PARTS_DETAILS',
  users: 'USERS',
  resetPassword: 'RESET_PWD',
  companyForm: 'COMPANY_FORM',
  dealerForm: 'DEALER_FORM',
  companyOperatorForm: 'COMPANY_OPERATOR_FORM',
  companyTechnicianForm: 'COMPANY_TECHNICIAN_FORM',
  companyOwnerForm: 'COMPANY_OWNER_FORM',
  dealerTechnicianForm: 'DEALER_TECHNICIAN_FORM',
  assignDealerClients: 'ASSIGN_DEALER_CLIENTS',
  addDealerClients: 'DEALER_CLIENT_FORM',
  preventiveMaintenance: 'PREVENTIVE_MAINTENANCE',
  addAttachment: 'ADD_ATTACHMENT',
  attachmentDetails: 'ATTACHMENT_DETAILS',
  equipmentForm: 'EQUIPMENT_FORM',
  equipmentDetails: 'EQUIPMENT_DETAILS',
  equipmentDocument: 'EQUIPMENT_DOCUMENTS',
  equipmentParts: 'EQUIPMENT_PARTS',
  addService: 'ADD_SERVICE',
  addRepair: 'ADD_REPAIR',
  equipment: 'EQUIPMENT_STACK',
  addDailyChecklist: 'ADD_DAILY_CHECKLIST',
  offlineSync: 'OFFLINE_SYNC',
};

export default screens;
